### ISSUE TITLE
how to get "tile" (HPoint) updated value with UnityRoomUsers

### ISSUE THREAD

**Issue by sep1** [sirjonasxx/G-Python#8]
The "tile" attribute of HUnityEntity class returns only the initial HPoint of an user which is not updated, unless you make a new room_users.request() which is not available with UnityRoomUsers. 

Am i right? Is there a solution for this without intercepting a RoomUserMove package?
Alternatively, how can i update the tile attribute of an user inside the room_users.room_users list?

Thanks for helping.

**Comment by kSlideHH** [comment]
You are right, request is not available in Unity. I'd have to figure out if theres a new alternative packet for this.

I will write something that will allow you to keep track of current user position.
You would need to parse the Status updates and apply them to the entities. I will add a method for this.

**Comment by kSlideHH** [comment]
Refs: https://github.com/sirjonasxx/G-Python/pull/9

This pull request resolves the issue

**Comment by sep1** [comment]
Thank you!
